#!/usr/bin/env ruby

require_relative './app'
require_relative './display'
require_relative './call_actions'

# class Main
# include Actions
def main
  app = App.new
  option = 0
  puts 'Welcome to School Library Rental App!'
  while option != 7
    Options.print_options
    option = gets.chomp.to_i
    if option.positive? && option < 7
      call_actions(option, app)
    elsif option == 7
      puts 'Thanks for using this App!'
    else
      puts 'Invalid option'
    end
  end
end
# end

main
